server {
    listen 80;
    server_name nhatom.online www.nhatom.online;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name nhatom.online www.nhatom.online;

    ssl_certificate /etc/letsencrypt/live/nhatom.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nhatom.online/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/nhatom;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
